### ISSUE TITLE
Token Missing?

### ISSUE THREAD

**Issue by gilcags** [PayMaya/wc-paymaya-payment-gateway#1]
Hi, is this the same plugin in the repo? The token is no longer required?

Also, does the plugin accepts recurring payments?

**Comment by micahbule** [comment]
Kindly define what token are we referring to.

Also, this does not support recurring payments at the moment.

**Comment by gilcags** [comment]
Copy. I just noticed that the old plugin has a token generated after activating the plugin and this new version does not. No worries.
