### ISSUE TITLE
Webhooks return Empty

### ISSUE THREAD

**Issue by gilcags** [PayMaya/wc-paymaya-payment-gateway#2]
When doing sandbox, upon testing WebHooks, it returns as 204 No Content.

The plugin generated a WebHook https://domain.com?wc-api=cynder_paymaya <- this is different than the old deprecated plugin. What should be placed here?

![Screenshot - 2020-11-04T114502 941](https://user-images.githubusercontent.com/48699362/98066996-80829780-1e93-11eb-9010-9caa7a129be3.png)

**Comment by micahbule** [comment]
The value for the webhook URLs should be your domain name with the corresponding API suffix `wc-api=cynder_paymaya`. For example, if you have a domain name of `https://some-valid.domain.com`, the value of the webhook URLs would be `https://some-valid.domain.com?wc-api=cynder_paymaya`.

**Comment by gilcags** [comment]
Correct, the webhooks are pre-defined once you activate the repo plugin and when you test it in the sandbox it will show this.

![Screenshot - 2020-11-04T134458 795](https://user-images.githubusercontent.com/48699362/98073780-0dcde800-1ea4-11eb-86e9-79c0b6ec929c.png)

**Comment by micahbule** [comment]
Hi @gilcags, the webhook endpoints being registered for the plugin doesn't require a response body as it is an endpoint that would receive the webhook request from Paymaya API. It primarily used to update orders after payments have been resolved.

**Comment by gilcags** [comment]
Copy that. Thanks for the clarification.
