### ISSUE TITLE
Why require address line 2 (`billing_address_2`)?

### ISSUE THREAD

**Issue by djramones** [PayMaya/wc-paymaya-payment-gateway#5]
Not really a bug, but this can be annoying for customers.

By default, the second address line is optional in the WC checkout form, but this plugin [sets it to required](https://github.com/PayMaya/wc-paymaya-payment-gateway/blob/8b7c2309696936d1101c87469cd72c3eee96bdf6/paymaya-top-level-hooks.php#L237). It means that, unless the site is configured (via WP's Customize feature) to also require this address line, customers will be told that the field is optional, and then presented with a conflicting error message after submitting the form that, actually, the field is required.

So, why? I understand the field is being passed to PayMaya's Checkout API, but is it required to be a non-empty value? Perhaps instead of requiring the field, a default value of, say, a dash can be passed when the field is left blank by users.

**Comment by micahbule** [comment]
I believe this is now resolved by https://github.com/PayMaya/wc-paymaya-payment-gateway/pull/10/commits/9e4a9a6d89e72f541cb18628c8fdb006fca679e9.
